---
- name: Ensure NFS mount point
  become: yes
  file:
    path: "{{ nfs_path }}"
    state: directory
    mode: 0755

- name: Ensure NFS
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nfs-common
  tags:
    - nfs

- name: Mount NFS drive
  mount:
    path: /data
    src: "{{ nfs_server_ip }}:{{ nfs_path }}"
    state: mounted
    fstype: nfs
    opts: rw

- name: Ensure RPC setup properly for NFS locks
  command: "{{ item }}"
  with_items:
  - systemctl enable rpc-statd
  - systemctl start rpc-statd
