---
- name: Ensure Docker Swarm initialization
  become: yes
  command: "docker swarm init --advertise-addr {{ swarm_master_ip }}"
  tags:
    - docker

- name: Ensure token is available on NFS
  become: yes
  shell: "docker swarm join-token -q worker > {{ nfs_path }}/swarm-token"
  tags:
    - docker
